server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=ewm-stats
spring.datasource.password=ewm-stats
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false